### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/runpod-volume/ComfyUI/output/ComfyUI_temp_tlerf_00001_.png

### ISSUE THREAD

**Issue by igbeller** [ashleykleynhans/runpod-worker-comfyui#1]
This error can happen In `rp_handler.py` when opening the image_path.
`FileNotFoundError: [Errno 2] No such file or directory: '/runpod-volume/ComfyUI/output/ComfyUI_temp_tlerf_00001_.png`

```
filename = image_filename['filename']
image_path = f'{VOLUME_MOUNT_PATH}/ComfyUI/output/{filename}'

with open(image_path, 'rb') as image_file:
    images.append(base64.b64encode(image_file.read()).decode('utf-8'))
```

Some workflows create temp images and add that to the overall output. Their type is "temp" `image_filename["type"] == "temp"` and they are put into in the `ComfyUI/temp`  folder. (see `ComfyUI/nodes.py` `save_images`)

For my case was good enough to skip the temp images

```
for image_filename in image_filenames:
    if image_filename['type'] is not "output":
        continue
```

Thanks for putting up the repo, it's great for a kickstart.

**Comment by ashleykleynhans** [comment]
This happens when you use preview image instead of save image in your workflow, change it to save image.
