### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by barber5** [ashleykleynhans/runpod-worker-comfyui#3]
Hey there, I've been using this and love it. One thing that might be worthwhile though is to start comfy with appending to the log file in case you have multiple workers going at once

in `start.sh`

`python main.py --port 3000 >> /workspace/logs/comfyui.log 2>&1 &`

**Comment by ashleykleynhans** [comment]
The log file is mostly for debugging purposes when the worker isn't functioning correctly. I am concerned that changing the logging to append will cause the disk to fill up quickly when there is a large number of requests.

**Comment by barber5** [comment]
Fair enough. Yes, I was trying to debug and it took me a bit to figure out why I wasn't seeing all that I expected in the logs
