### ISSUE TITLE
API never starts and stuck at `Service not ready yet. Retrying..."`

### ISSUE THREAD

**Issue by kilimchoi** [ashleykleynhans/runpod-worker-comfyui#5]
I deployed your pre-built docker image and tried making the request but in the logs I just see, 
`{"requestId": null, "message": "Service not ready yet. Retrying...", "level": "INFO"}`

any ideas?

**Comment by ashleykleynhans** [comment]
You didn't install stuff onto your network volume correctly.

**Comment by kilimchoi** [comment]
Followed the instructions to run the installation script as specified in the readme in the network volume but still getting the same error. are you not able to reproduce it? I can repro just by creating a new volume, run the installation script on the pod, deploy and making a post request.

**Comment by ashleykleynhans** [comment]
Please find an alternate solution, I am no longer supporting RunPod because they keep banning me from their Discord.
